language: android
sudo: required
dist: trusty

android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - add-on
    - extra
    - extra-android-m2repository

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"
  - export JAVA_HOME=~/oraclejdk11
  - export PATH="$JAVA_HOME/bin:$PATH"
  - ~/bin/install-jdk.sh --target "/home/travis/oraclejdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "BCL"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script:
  - echo "android.useAndroidX=true" > gradle.properties
  - ./gradlew -PdisablePreDex check
  - cd onomap-geoserver/geoserver
  - pwd
  - travis_retry ./gradlew test --info --stacktrace

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache


