language: android
jdk:
  - oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-29
  - android-29
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services

before_install:
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew -PdisablePreDex check
  - cd onomap-geoserver/geoserver
  - pwd
  - travis_retry ./gradlew test --info --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
